services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: event-ticketing-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: event-ticketing
      RABBITMQ_DEFAULT_PASS: ticketing1_#
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
